config/routes.rb
Rails.application.routes.draw do

  get 'static/home'

  get 'static/about'

  root 'static#home'
  get '/about', to: 'static#about'
  
  # root "projects#index" # need to set this as the root route 
  
  resources :projects

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_pars)

    if @project.save
      redirect_to projects_path
    else
      render :new
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_pars)
      redirect_to projects_path
    else
      render :edit
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to projects_path
  end

  private
    def project_pars
      params.require(:project).permit(:name, :notes, :grade)
    end

end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/static_helper.rb
module StaticHelper
end

app/views/layouts/_navbar.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'About', about_path %>
<%= link_to 'Projects', projects_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>W4d2ClimbingApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_for @project do |i| %>
  <hr>
  <%= i.label :name %>
  <%= i.text_field :name %>
  <br>
  <%= i.label :grade %>
  <%= i.text_field :grade %>
  <br>
  <%= i.label :notes %>
  <%= i.text_area :notes %>
  <br>

  <%= i.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit <%= @project.name%></h1>
<%= render 'form' %>

app/views/projects/index.html.erb
<h1> Projects </h1>
<p><%= link_to 'New Project', new_project_path %></p>
<% @projects.each do |project| %>
  <h2><%= project.name %></h2>
  <%= link_to 'Project Details', project_path(project) %>
  <%= link_to 'Edit', edit_project_path(project) %>
  <%= link_to 'Delete', project, method: :delete %>
<% end %>

app/views/projects/new.html.erb
<h1>New Project</h1>
<%= render 'form' %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<h4><%= @project.grade %></h4>
<p><%= @project.notes %></p>
<%= link_to 'Back', projects_path %>